"""empty message

Revision ID: 9080c17ad80d
Revises: 
Create Date: 2020-07-08 21:20:16.638307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9080c17ad80d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_table',
    sa.Column('task_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_name', sa.String(length=128), nullable=True),
    sa.Column('task_description', sa.String(length=128), nullable=True),
    sa.Column('task_start_date', sa.DateTime(), nullable=True),
    sa.Column('task_complete_date', sa.DateTime(), nullable=True),
    sa.Column('task_assignee', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('task_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_table')
    # ### end Alembic commands ###
