"""empty message

Revision ID: 9ac0e2438b67
Revises: 
Create Date: 2020-07-24 13:19:33.441874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ac0e2438b67'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_table',
    sa.Column('user_email', sa.String(length=128), nullable=False),
    sa.Column('first_name', sa.String(length=128), nullable=True),
    sa.Column('last_name', sa.String(length=128), nullable=True),
    sa.Column('date_of_birth', sa.DateTime(), nullable=True),
    sa.Column('user_password', sa.String(length=128), nullable=True),
    sa.Column('mobile_number', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('user_email')
    )
    op.create_table('login_details',
    sa.Column('user_email', sa.String(length=128), nullable=False),
    sa.Column('user_password', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['user_email'], ['user_table.user_email'], ),
    sa.PrimaryKeyConstraint('user_email')
    )
    op.create_table('task_table',
    sa.Column('user_email', sa.String(length=128), nullable=True),
    sa.Column('task_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_name', sa.String(length=128), nullable=True),
    sa.Column('task_description', sa.String(length=128), nullable=True),
    sa.Column('task_start_date', sa.DateTime(), nullable=True),
    sa.Column('task_complete_date', sa.DateTime(), nullable=True),
    sa.Column('task_assignee', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['user_email'], ['user_table.user_email'], ),
    sa.PrimaryKeyConstraint('task_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_table')
    op.drop_table('login_details')
    op.drop_table('user_table')
    # ### end Alembic commands ###
