"""empty message

Revision ID: be4c49977f4c
Revises: 4042d1aa102e
Create Date: 2020-07-22 22:15:10.905684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be4c49977f4c'
down_revision = '4042d1aa102e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_table', sa.Column('date_of_birth', sa.DateTime(), nullable=True))
    op.add_column('user_table', sa.Column('user_password', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_table', 'user_password')
    op.drop_column('user_table', 'date_of_birth')
    # ### end Alembic commands ###
